Linter Added
mfadhili/ReviewTest pull request #1
Opened 2022-09-27 15:05 UTC by mfadhili

Demo review

2022-09-27 15:22 UTC, mfadhili commented on css/style.css
> +	padding-right: 8%;
check indentation. Indentation should be 2spaces

2022-09-27 15:22 UTC, mfadhili commented on css/style.css
> +	display: inline-block;
use proper formart for a starndard

2022-10-03 08:49 UTC, mfadhili commented on index.html
>  			<h3>We are Web Developer.</h3>
the changes are okay

2022-10-03 11:33 UTC, mfadhili reviewed
Check these corrections please

2022-10-03 11:33 UTC, mfadhili commented on css/style.css
>  nav ul li a:hover{
fix the CSS file to conform to StyleLint

2022-10-03 11:43 UTC, franclobo requested changes
Hi, @mfadhili, 

Good job so far!
You are doing it well 👍🏽 there are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Comments are clear and easy to understand ✔️
- Good use of inline comments ✔️
- Correct use of summary ✔️

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

- [ ] Please 🙏🏽 instead of giving orders, make suggestions. "I think it would be better to use semantic tags" sounds nicer than "Use semantic tags," doesn't it?
- [ ]  Please 🙏🏽 remember to be polite and clear in your comments - your job here is to help another person improve in a friendly way.
- [ ] Please 🙏🏽 explain the reason why a change is requested.
- [ ]  Kindly you can include emojis and gifs to make your code review more human-friendly 👽.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-03 12:00 UTC, mfadhili commented on css/style.css
> +.card .button:hover {
You're doing great fixing the linter errors :+1: 
To better improve, try also adding a space before the curly brace.
Keep it up :1st_place_medal:

2022-10-03 12:03 UTC, mfadhili commented on css/style.css
> -}
you're almost there :clap: 
a few more corrections and you'll be done. :man_dancing: :woman_dancing: 
to make it better, Id suggest that you check the linters report.

Cheers and Happy coding!clapclapclap

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2022-10-03 12:10 UTC, GiuseppeTG commented
Hi @mfadhili  👋 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🥇 : 
Congratulations! 🎉 

![Alt Text](https://media3.giphy.com/media/nXxOjZrbnbRxS/giphy.gif)

## Highlights
✅ You sounded more kind
✅ Good use of emojis
✅ Made suggestions instead of giving orders

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-03 13:41 UTC, merged